version: '3.8'
services:
  database:
    image: mysql
    container_name: database
    restart: unless-stopped
    env_file: ./.database.env
    networks:
      - papisNetwork

  backend:
    depends_on:
      - database
    image: user-app-test
    container_name: backend
    env_file: ./.backend.env
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
  
    networks:
      - papisNetwork

networks:
  papisNetwork:  

