version: '3.8'
services:
  database:
    image: mysql
    container_name: database
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_USER=$DATABASE_USER
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE
    networks:
      - papisNetwork

  backend:
    depends_on:
      - database
    image: papis212/user-app 
    container_name: app_user_c
    env_file: ./.env
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
    environment:
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE=$DATABASE
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
    networks:
      - papisNetwork

networks:
  papisNetwork:  

