name: CI/CD pipeline for user application

on:
  push:
    branches:
      - master

jobs:
  scan-trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code du repo
        uses: actions/checkout@v2

      - name: Mise en place de python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation des  dependences
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Installation de trivy
        run: |
          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.38.3/trivy_0.38.3_Linux-64bit.deb -o trivy.deb
          sudo dpkg -i trivy.deb  # Installer Trivy

      - name: Debut du scan de l'application avec trivy
        run: |
          trivy fs . --skip-update --format json -o trivy-results.json
          
      - name: Upload Trivy Report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy-results.json

  setup-app:
    runs-on: ubuntu-latest
    needs: scan-trivy

    steps:
      - name: Recuperation du code l'application et preparation pour le build
        uses: actions/checkout@v2

      - name: Installation de Python pour le build de l'application
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation des dependes pour le build de l'app
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Execution de l'application pour test
        run: |
          python3 main.py

  deploy:
    runs-on: ubuntu-latest
    needs: setup-app

    steps:
      - name: Recuperation du code , Debut du deploiement dans heroku
        uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}   
          heroku_email: ${{secrets.HEROKU_EMAIL_ADRESS}}
